BEGIN;

CREATE TABLE IF NOT EXISTS clients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name TEXT NOT NULL,
    phone VARCHAR(32),
    email VARCHAR(255),
    preferred_contact_channel VARCHAR(32),
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS vehicles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
    brand VARCHAR(80) NOT NULL,
    model VARCHAR(120) NOT NULL,
    year INTEGER,
    vin VARCHAR(64) UNIQUE,
    plate VARCHAR(32),
    color VARCHAR(80),
    access_pin_hash VARCHAR(255) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_vehicles_access_pin_hash UNIQUE (access_pin_hash)
);

CREATE TABLE IF NOT EXISTS vehicle_qr_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id BIGINT NOT NULL REFERENCES vehicles(id) ON DELETE CASCADE,
    qr_id VARCHAR(120) NOT NULL UNIQUE,
    public_slug VARCHAR(160) NOT NULL UNIQUE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    activated_at TIMESTAMPTZ,
    revoked_at TIMESTAMPTZ,
    last_scanned_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS service_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id BIGINT NOT NULL REFERENCES vehicles(id) ON DELETE CASCADE,
    service_type VARCHAR(40) NOT NULL,
    title VARCHAR(160),
    installed_at DATE NOT NULL,
    warranty_expires_at DATE,
    washing_recommendations TEXT,
    care_instructions TEXT,
    internal_notes TEXT,
    is_public BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_service_records_service_type
        CHECK (service_type IN ('PPF', 'Wrap', 'Ceramic', 'Detailing', 'Maintenance'))
);

CREATE TABLE IF NOT EXISTS service_media (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_record_id BIGINT NOT NULL REFERENCES service_records(id) ON DELETE CASCADE,
    media_url TEXT NOT NULL,
    media_type VARCHAR(24) NOT NULL DEFAULT 'image',
    caption TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0,
    is_public BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_service_media_media_type
        CHECK (media_type IN ('image', 'video', 'document'))
);

CREATE INDEX IF NOT EXISTS ix_clients_phone ON clients(phone);
CREATE INDEX IF NOT EXISTS ix_clients_email ON clients(email);
CREATE INDEX IF NOT EXISTS ix_vehicles_client_id ON vehicles(client_id);
CREATE INDEX IF NOT EXISTS ix_vehicles_is_active ON vehicles(is_active);
CREATE INDEX IF NOT EXISTS ix_vehicle_qr_codes_vehicle_id ON vehicle_qr_codes(vehicle_id);
CREATE INDEX IF NOT EXISTS ix_vehicle_qr_codes_is_active ON vehicle_qr_codes(is_active);
CREATE INDEX IF NOT EXISTS ix_service_records_vehicle_id ON service_records(vehicle_id);
CREATE INDEX IF NOT EXISTS ix_service_records_service_type ON service_records(service_type);
CREATE INDEX IF NOT EXISTS ix_service_records_warranty_expires_at
    ON service_records(warranty_expires_at);
CREATE INDEX IF NOT EXISTS ix_service_media_service_record_id
    ON service_media(service_record_id);
CREATE INDEX IF NOT EXISTS ix_service_media_public_order
    ON service_media(service_record_id, is_public, sort_order);

COMMIT;
